global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.IO;
global using System.Net.Http;
global using NovelTTSApp.Core.Entities;
global using NovelTTSApp.Core.Interfaces;
